---
title: "Week 03: Reporting your data analysis"
subtitle: "Creating inputs and organizing a short data analytics report with AI"
date: "2025-03-20"
---

::: {.hero-section}
::: {.container}
::: {.hero-title}
Week 03: Reporting your data analysis
:::
::: {.hero-subtitle}
Creating inputs and organizing a short data analytics report with AI
:::
:::
:::


## Objectives 

### Summary:  

How to organize a short data analytics report? The job includes choosing and creating relevant plots, running regression. 
The class will exlopre how we can use AI to assist in these tasks.

### Details

* Understand how to connect an empirical question to data 
* Create relevant visualizations and tables using AI.
* Learn to critically assess reports with the help of AI tools.

## Preparation BEFORE class

* Background reading: Békés-Kézdi (2021) Chapters 3-4, 7-10
* Download the [WVS_GDP_merged_data.csv](/data/VWS/WVS_GDP_merged_data.csv). This is an aggregated, cleaned subset of the 7th Wave of WVS dataset merged with GDP data from World Bank

### The data

* This is aggregated data: country level
* Year: Wave 7 of the WVS -- survey was conducted at different years. 
* Combined with World Bank data: at year when survey was conducted
 * GDP: level USD, level USD PPP, level  USD PPP per capita
 * population

## Class plan

### Review Readme assignment

* Q+A
* Verify, verify, verify (AI is good but rarely perfect)

### Starting presentation about prompting

[slideshow](https://gabors-data-analysis.com/courses/da-w-ai-2025/da-w-ai-02-prompting)

### How does a good report look like?

  *	How to write a good short report: structure
  *	good graphs and tables
 	*	Make sure precise language. Recap on causal language.

### Problems with AI generated reports.
 
 Use  AI as input (like advanced google search) not as output writer 

 Because
 * Creates "average" / generic / bland / repetitive text
 * Convincing but not precise
 * Not your style and not your exact plan
 * Too broad (like adds further research)

### NO AI

Form 2-3 member groups freely

1. Each group: Choose one these pre-defined research questions:
  * Is there a relationship between income level and trust? 
  * Is there a relationship between income level and happiness? 
  * Is there a relationship between income level and gender attitudes?
2. Choose the relevant variables to answer your question (you can use AI to understand variables like in [week2](/week02)
3. Design a plan for a report on the topic: list of exhibits (graphs, tables). Do not write code (yet)
4. Discuss plans

### AI 1

Try get a report with a single prompt.
* Hint: translate your plan into a prompt using ideas from the intro. 

### AI 2

* Showcase an iterative process where key exhibits are created

## End of Week Discussion points

* Compare single and multi-step approach generating reports?
* How good is AI in creating good enough vs exactly as planned graphs?
* What is happiness? :-)