---
title: "Course Assignments"
---

Assignments are available for all classes

**Important to note for assignments: **
* Use AI but do not submit something that was created by AI. AI is your assistant.
* One of the goals of the course is to practice this. 

## Assignment 1: Reproduce an FT graph

Look at [this graph](week01/assets/ft-liberation-day-usd-yield-2025-04-11.jpg) from Financial Times. Your task is to recreate this figure using real-world data. 

[Assignment Details](assignments/assignment_01.qmd)

## Assignment 2: Creating a readme doc

In this assignment, you will create a readme document by asking for AI assistance.

[Assignment Details](assignments/assignment_02.qmd)

## Assignment 3: Create a report

Continue with the research question you had chosen in class. Use AI iteratively to **help** you create a report. 

[Assignment Details](assignments/assignment_03.qmd)

## Assignment 4: Join tables analysis

Create groups of 2-3 people who use the same coding language. Ask AI to give you a list of research questions that can be answered using many (at least 4) of the hotel data sets provided.

[Assignment Details](assignments/assignment_04.qmd)

## Assignment 5: Text sentiment analysis

Student-Specific Text Sentiment Analysis -- Compare manual ratings with AI-generated ratings.

[Assignment Details](assignments/assignment_05.qmd)

## Assignment 6: Text  analysis: guessing gender in text

Create pipeline for guessing the speaker's gender.

[Assignment Details](assignments/assignment_06.qmd)


## Assignment 7: Simulation app

Create a simulation app of an important statistical phenomenon.

[Assignment Details](assignments/assignment_07.qmd)

## Assignment 8: Design an IV

Think about an identification problem and interate to find a good IV. 

[Assignment Details](assignments/assignment_08.qmd)
