---
title: "Weekly Content"
---

## Week01: LLM Review

What are LLMs, how is the magic happening. A non-technical brief intro. How to work with LLMs? Plus ideas on applications. Includes suggested readings, podcasts, and vids to listen to. 

[Content](week01/)

**Which AI?** See [my take on current models](week01/assets/which-ai.html). As of *May 2025*. 

## Week02: Data and code discovery and documentation with AI

Learn how to write a clear and professional code and data documentation. LLMs are great help once you know the basics. 

Case study: World Values Survey. Data is at [WVS](data/VWS)

[Content](week02/)

## Week 03: Writing Reports

You have your data and task, and need to write a short report. We compare different options with LLM, from one-shot prompt to iteration. 

Case study: World Values Survey. Data is at [WVS](data/VWS)

[Content](week03/)

## Week04: Data wrangling, joining tables

When asked about what I shall add to my textbook, David Card, the Nobel winning empirical economist told me that I shall spend time with joining tables. Here we go. 

Case study: simulated Austrian hotels. Data is at [hotels](data/austria-hotels)

[Content](week04/)

## Week05: Text as data 1 -- intro lecture

No course of mine can escape football (soccer). Here we look at post-game interviews to learn basics of text analysis and apply LLMs in what they are best - context dependent learning. Two class series. First is more intro to natural language processing. 

Case study: football post-game interviews. Data is at [interviews](data/interviews)

[Content](week05/)

## Week06: Text as data 2 -- practice

Second class, now we are in action. How does LLM compare to humans? 

Case study: football post-game interviews. Data is at [interviews](data/interviews)

[Content](week06/)