---
title: "Assignment 2: Create a readme document"
---

### Task

In this assignment you ask for AI assistance to create a readme document.

* First, consider the VWS survey we used in class: [codebook](/data/VWS/codebook.pdf), [sample data](/data/WVS_random_subset500.csv)
* Second, pick a research question using the VWS data. This can be broad or specific, ask AI for ideas.
* Which variables would you use to investigate your research question? Pick the most relevant ones (min 8, max 25).
* Create a single README.md (markdown format), considering these variables only. The readme includes:

**Option A (easier)**

* Key information about the dataset itself (you should figure out what this key information is, based on lectures and examples)
* Key variable descriptions
* A descriptive statistics table for 5 of your most important chosen variables

**Option B (more advanced)**

* In addition to Option A's points, it describes a folder structure you would use to work with this data.


### Deliverables

* Deliverable 1: Your final README.md file and code. (lastname_firstname_dawai_week01_readme.md) (16 points)
* Deliverable 2:
  What advice would you give to a fellow student data analyst about **using AI to create a README document**? (lastname_firstname_dawai_week01_advice.txt) (4 points)
    * List 2-3 pieces of advice, based on your own experience of using AI for this particular task.

**Important notice**

* Do not use AI to generate your advice. I am interested in hearing your personal examples and reflections, not AI-generated suggestions.