---
title: "Student-specific sentiment analysis"
---

### Task

Student-specific sentiment analysis for a set of texts -- compare manual rating vs AI generated rating.

Steps:

* Download [interview text file](/data/interviews/interview-texts-only.xlsx). Generate 25 random numbers between 1 and 121 (_no duplicates_). These will be the interviews you will evaluate. Filter for those interviews, and save the file as lastname_firstname_sentiment_rated.xlsx.
* Go through the interviews and manually rate the sentiment of the manager (25 in total).
* Feed the entire manager interview (excluding your ratings) into an AI of your choice and compare the AI-generated sentiment rating to your initial manual rating.
* Both exercises incorporate the guidelines from [here](/week05/assets/sentiment-guidelines.html).
* Write one paragraph that compares your manual ratings to the AI-generated ratings and summarizes similarities and deviations.

### Deliverables:

* File with your manual and AI-generated ratings: lastname_firstname_sentiment_rated.xlsx.
* Text file with one paragraph summarizing similarities and deviations: lastname_firstname_sentiment_eval.txt/