---
title: "Create a report"
---

Continuing with the research question you picked in class.

Iteratively use AI to **help** you create a report.

**Important**

* AI is your assistant, use it as an input, not an output. Never submit an AI-generated report as is, always write, review, and edit.

### Task

**Option A (easier)**

  * Think in terms of two variables ($x$ and $y$).
    * Pick a single variable or a combined index of variables.
    * Pick the GDP variable.
    * Think about causality.
  * Create one carefully designed graph to illustrate the relationship (Graph 1).
  * Explain your choices/decisions at each step (i.e. why you picked certain variables).
  * Create a concluding paragraph summarizing your work and summarizing your findings in 80-100 words.

**Option B (more advanced)**

* In **addition to Option A's tasks**, create another graph that shows heterogeneity in country size groups, using population (Graph 2).
* Run a regression analysis and interpret the coefficients.

### Deliverables

* Deliverable 1: Submit a max 1-1.5 page report in .pdf format (with supporting material) (lastname_firstname_dawai_week03_report.pdf) (12 points)
* Deliverable 2: Submit code or provide a link to it. (4 points)
* Deliverable 3:
  What advice would you give to a fellow student data analyst about using AI to create a report? (lastname_firstname_dawai_week01_advice.txt) (4 points)
    * List 2-3 pieces of advice, based on your own experience of using AI for this particular task.

**Important:**

* If applicable, upload your report to the `student folder called Reports` on moodle or similar service -- this is for next class.
* Important: Do not use AI to generate your advice. I am interested in hearing your personal examples and reflections, not AI-generated suggestions.
* First 20min of next class, each group will read another group's report and discuss what is good and bad about the report.