---
title: "Week 06: Sentiment Analysis with AI"
subtitle: "Using API to AI to create data from text"
date: "2025-05-20"
---

::: {.hero-section}
::: {.container}
::: {.hero-title}
Week 06: Sentiment Analysis with AI
:::
::: {.hero-subtitle}
Using API to AI to create data from text
:::
:::
:::



## Overview
Continue using text for research with AI

### Learning Outcomes
By the end of the session, students will:

* Gain hands-on experience with sentiment analysis.
* Have experience integrating NLP in research
* Think about what is ground truth

## Using APIs

### Basics and setup

[How to use APIs](assets/api-use.html) 

[Get an API Key (ChatGPT and Claude)](assets/get-ai-api-key.html) 

### Examples

[Simple walkthrough with GDP data](assets/walkthrough-wb-fred.html)  -- uses World Bank and FRED APIs

[Bit harder walkthrough with football data](assets/walkthrough-fbref.html)  -- uses FBREF soccer data. Guess the club for example. 

### More advanced stuff

[More advanced knowledge on APIs](assets/api-advanced.html)  -- *how* APIs work


### Materials

**Datasets** 

- texts (text_id level)
- games info (such as results, text_id level)
- class-ratings (human, AI ratio, text_id*student level)
- domain-rating (text_id level)
- class-rating-aggregated (text_id level)

**code**

code that creates the combined data
  
## Preparation

* Download the combined data from Moodle
  * Note: win, draw -- need encode loss

## Class tasks
   
### Discussion 1

* Your experience regarding human vs ai ratings.
* What was difficult and easy as human rater

### Data Analysis

* Take the aggregated file and ask AI for a readme. Discuss what is in the data
* Compare human, domain lexicon and AI rating. For human and AI take the average.
* Think of an interesting comparison using AI rating
* Compare results by human and lexicon rating

### Discussion 2

* What is ground truth

### How to integrate AI into research

* combine data with text
* think RQ and how you'd use AI

## Additional tasks if time permits

### predict gender and result

* Show AI all texts and ask to predict the gender of speaker
* Show AI all texts and ask to predict the result (manager's team won, drew, lost)